version: '2'

services:
  redis:
    image: sameersbn/redis:latest
    restart: unless-stopped
    tty: true
    stdin_open: true
    command:
      - --loglevel warning
    expose:
      - "6379"
    volumes:
      - redis:/var/lib/redis:Z
    labels:
      io.rancher.container.pull_image: always

  postgres:
    image: sameersbn/postgresql:latest
    restart: unless-stopped
    tty: true
    stdin_open: true
    expose:
      - "5432"
    volumes:
      - postgres:/var/lib/postgresql/data:Z
    env_file:
      - ${PWD}/env/postgres.dist.env
      - ${PWD}/env/postgres.env
    labels:
      io.rancher.container.pull_image: always

  gitlab:
    image: sameersbn/gitlab:latest
    restart: unless-stopped
    stdin_open: true
    tty: true
    depends_on:
      - redis
      - postgres
    expose:
      - "22"
      - "80"
      - "5500"
    volumes:
      #- /etc/letsencrypt/production/certs:/certs:ro
      - ${PWD}/certs:/certs
      - data:/home/git/data:Z
      - log:/var/log/gitlab
    env_file:
      - ${PWD}/env/gitlab.dist.env
      - ${PWD}/env/gitlab.env
    labels:
      service: gitlab
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: redis, registry, postgres

  registry:
    image: registry:latest
    restart: unless-stopped
    tty: true
    stdin_open: true
    expose:
      - "5000"
    volumes:
      #- /etc/letsencrypt/production/certs:/certs:ro
      - ${PWD}/certs:/certs
      - registry:/registry
    env_file:
      - ${PWD}/env/registry.dist.env
      - ${PWD}/env/registry.env
    labels:
      io.rancher.container.pull_image: always

  runner:
    image: gitlab/gitlab-runner:latest
    restart: unless-stopped
    tty: true
    stdin_open: true
    volumes:
      - ${PWD}/runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      io.rancher.container.pull_image: always

volumes:
  data:
    driver: "local"
  log:
    driver: "local"
  postgres:
    driver: "local"
  redis:
    driver: "local"
  registry:
    driver: "local"
