version: '2'

services:
  redis:
    image: sameersbn/redis:latest
    restart: unless-stopped
    tty: true
    stdin_open: true
    command:
      - --loglevel warning
    volumes:
      - ${PWD}/redis:/var/lib/redis:Z
    labels:
      io.rancher.container.pull_image: always

  postgresql:
    image: sameersbn/postgresql:latest
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/postgresql:/var/lib/postgresql:Z
    env_file:
      - ${PWD}/env/postgresql.dist.env
      - ${PWD}/env/postgresql.env
    labels:
      io.rancher.container.pull_image: always

  gitlab:
    image: sameersbn/gitlab:latest
    restart: unless-stopped
    stdin_open: true
    tty: true
    depends_on:
      - redis
      - postgresql
    ports:
      - "40180:80"
      - "5500:5500"
      - "40122:22"
    volumes:
      - ${PWD}/gitlab:/home/git/data:Z
      - ${PWD}/logs:/var/log/gitlab
      - ${PWD}/certs:/certs
    env_file:
      - ${PWD}/env/gitlab.dist.env
      - ${PWD}/env/gitlab.env
    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: redis, postgresql, registry

  registry:
    image: registry:latest
    restart: unless-stopped
    tty: true
    stdin_open: true
    volumes:
      - ${PWD}/gitlab/shared/registry:/registry
      - ${PWD}/certs:/certs
    env_file:
      - ${PWD}/env/registry.dist.env
      - ${PWD}/env/registry.env
    labels:
      io.rancher.container.pull_image: always

  runner:
    image: gitlab/gitlab-runner:latest
    restart: unless-stopped
    tty: true
    stdin_open: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/runner/config:/etc/gitlab-runner
    labels:
      io.rancher.container.pull_image: always
