version: '2'
services:

  redis:
    scale: 1
    start_on_create: true
    health_check:
      port: 6379
      interval: 60000
      initializing_timeout: 60000
      reinitializing_timeout: 60000
      unhealthy_threshold: 3
      strategy: none
      healthy_threshold: 2
      response_timeout: 2000

  postgresql:
    scale: 1
    start_on_create: true
    health_check:
      port: 5432
      interval: 60000
      initializing_timeout: 60000
      reinitializing_timeout: 60000
      unhealthy_threshold: 3
      strategy: none
      healthy_threshold: 2
      response_timeout: 2000

  gitlab:
    scale: 1
    health_check:
      port: 80
      request_line: GET / HTTP/1.0
      interval: 60000
      initializing_timeout: 60000
      reinitializing_timeout: 60000
      unhealthy_threshold: 3
      strategy: none
      healthy_threshold: 2
      response_timeout: 2000

  registry:
    scale: 1
    start_on_create: true
    health_check:
      port: 5000
      interval: 60000
      initializing_timeout: 60000
      reinitializing_timeout: 60000
      unhealthy_threshold: 3
      strategy: none
      healthy_threshold: 2
      response_timeout: 2000

  runner:
    scale: 1
    start_on_create: true
